---
output: html_document
editor_options: 
  chunk_output_type: inline
---
#Load libraries
```{r}
library(readxl)
library(tidyr)  
library(dplyr)  
library(ggsignif)
library(ggplot2)
library(broom) 
library(rstatix)
library(ggpubr)
library(stringr)
library(viridis)
library(emmeans)
library(purrr)
library(car)
library(extrafont)
library(plotrix)

output_dir <- "../Flow cyto (PBMCs)/plots_output/"
dir.create(output_dir, showWarnings = FALSE)
custom_colors <- c("#330597","#8405a7","#b12a90","#d35171","#f68f44","#fec029")
```

#Load data
```{r}
data_PFNA <- read.csv("../Flow cyto (PBMCs)/Jan 9 2025 PFNA/09-Jan-2025.wsp FlowJo table.csv") %>%
  mutate(Chemical = "PFNA")
data_PFOA <- read.csv("../Flow cyto (PBMCs)/Dec 19 2024 PFOA/20-Dec-2024 (UNMIXING 1).wsp FlowJo table.csv") %>%
  mutate(Chemical = "PFOA")
data_PFDA <- read.csv("../Flow cyto (PBMCs)/Jan 16 2025 PFDA/16-Jan-2025.wsp FlowJo table.csv") %>%
  mutate(Chemical = "PFDA")
data_PFHxS <- read.csv("../Flow cyto (PBMCs)/Jan 16 2025 PFHxS/16-Jan-2025.wsp FlowJo table.csv") %>%
  mutate(Chemical = "PFHxS")
data_PFHxS$X <- str_replace(data_PFHxS$X, "PFHxS\\+", "PFHxS +") #typo in one of the conditions
data_PFOS <- read.csv("../Flow cyto (PBMCs)/Dec 12 2024 (new) PFOS/20-Dec-2024.wsp FlowJo table.csv") %>%
  mutate(Chemical = "PFOS")
data_GenX <- read.csv("../Flow cyto (PBMCs)/Jan 31 2025 GenX/31-Jan-2025.wsp FlowJo table.csv") %>%
  mutate(Chemical = "GenX")

data <- bind_rows(data_PFNA, data_PFOA, data_PFDA, data_PFHxS, data_PFOS, data_GenX)

cleaned_data <- data %>%
  mutate(
    Sample = word(X, 1),
    Group = word(X, 2),
    Treatment = str_remove(X, ".*? .*? ") %>% 
                str_remove("WLSM") %>%        
                str_remove("\\.fcs") %>%      
                str_trim()                    
  ) %>%
  filter(Group %in% c("M1", "M2", "M3", "M4", "F1", "F2", "F3", "F4")) %>%
  rename(
    CD3 = cells.Single.Cells.live.CD3...Freq..of.Parent....,
    CD3_fi = cells.Single.Cells.live.CD3.CFSE...Area.subset...Mean..CFSE...Area.,
    CD4 = cells.Single.Cells.live.CD4...Freq..of.Parent....,
    CD4_fi = cells.Single.Cells.live.CD4.CFSE...Area.subset...Mean..CFSE...Area.,
    CD8 = cells.Single.Cells.live.CD8...Freq..of.Parent....,
    CD8_fi = cells.Single.Cells.live.CD8.CFSE...Area.subset...Mean..CFSE...Area.,
    live = cells.Single.Cells.live...Freq..of.Parent....,
    CD3_ud = cells.Single.Cells.live.CD3.CFSE...Area.subset.undivided...Freq..of.Parent....,
    CD4_ud = cells.Single.Cells.live.CD4.CFSE...Area.subset.undivided...Freq..of.Parent....,
    CD8_ud = cells.Single.Cells.live.CD8.CFSE...Area.subset.undivided...Freq..of.Parent....,
    Ms = cells.Single.Cells.live.Remainder...Freq..of.Parent....,
    Ms_fi = cells.Single.Cells.live.Remainder...Mean..CFSE...Area.,
    Ms_ud = cells.Single.Cells.live.Remainder.undivided...Freq..of.Parent....
  ) %>%
  mutate(
    Sex = ifelse(str_starts(Group, "M"), "Male", "Female"),
    Smokers = ifelse(Group %in% c("M1", "M3", "M4", "F1"), "Smoker", "Non-Smoker")
  ) %>%
  select(Chemical, Sample, Group, Treatment, Sex, Smokers, CD3, CD3_fi, CD4, CD4_fi, CD8, CD8_fi, live, CD3_ud, CD4_ud, CD8_ud, Ms, Ms_fi, Ms_ud)

cleaned_data <- cleaned_data %>%
  mutate(
    Treatment = case_when(
      str_detect(Treatment, "PFHxS\\+ PHA100uM") ~ "PFHxS + PHA100uM",
      str_detect(Treatment, "PFHxS\\+ PHA0.5uM") ~ "PFHxS + PHA0.5uM",
      TRUE ~ Treatment  
    )
  )

cleaned_data <- cleaned_data %>%
  mutate(
    Treatment = str_trim(Treatment),  
    Treatment = case_when(
      str_detect(Treatment, "vehicle control \\+ LPS") ~ "LPS + Vehicle",
      str_detect(Treatment, "vehicle control \\+ PHA") ~ "PHA + Vehicle",
      str_detect(Treatment, "PFNA") ~ str_replace(Treatment, "PFNA \\+ ", ""),
      str_detect(Treatment, "PFOA") ~ str_replace(Treatment, "PFOA \\+ ", ""),
      str_detect(Treatment, "PFDA") ~ str_replace(Treatment, "PFDA \\+ ", ""),
      str_detect(Treatment, "PFOS") ~ str_replace(Treatment, "PFOS \\+ ", ""),
      str_detect(Treatment, "PFHxS") ~ str_replace(Treatment, "PFHxS \\+ ", ""),
      str_detect(Treatment, "GenX") ~ str_replace(Treatment, "GenX \\+ ", ""),
      TRUE ~ Treatment
    )
  )
numeric_columns <- c("CD3", "CD4", "CD8",  "live", "CD3_ud", "CD4_ud", "CD8_ud", "CD8_fi", "CD4_fi", "CD3_fi", "Ms", "Ms_fi", "Ms_ud")
cleaned_data <- cleaned_data %>%
  mutate(across(all_of(numeric_columns), ~ as.numeric(gsub(",", ".", .))))

ud_columns <- grep("_ud$", names(cleaned_data), value = TRUE)
for (col in ud_columns) {
  new_col_name <- sub("_ud$", "_divided", col)
  cleaned_data[[new_col_name]] <- 100 - cleaned_data[[col]]
}

cleaned_data <- replace(cleaned_data, is.na(cleaned_data), 0)

# Normalize
 normalize_by_vehicle <- function(df) {
  numeric_columns <- c("CD3_fi", "CD4_fi", "CD8_fi", "Ms_fi")
  
  for (col in numeric_columns) {
    vehicle_col <- paste0(col, "_vehicle")  
    df <- df %>%
      group_by(Chemical, Group, Treatment_Type = ifelse(str_detect(Treatment, "LPS"), "LPS", "PHA")) %>%
      mutate(
        !!sym(vehicle_col) := if_else(Treatment %in% c("LPS + Vehicle", "PHA + Vehicle"), .data[[col]], NA_real_)
      ) %>%
      mutate(before_na_fill = !!sym(vehicle_col)) %>%
      mutate(!!sym(vehicle_col) := zoo::na.locf(!!sym(vehicle_col), na.rm = FALSE)) %>%
      mutate(!!sym(vehicle_col) := zoo::na.locf(!!sym(vehicle_col), fromLast = TRUE)) %>%
      mutate(after_na_fill = !!sym(vehicle_col)) %>%
      mutate(!!sym(col) := .data[[col]] / !!sym(vehicle_col)) %>%
      ungroup()
  }
  
  df <- df %>%
    mutate(across(all_of(numeric_columns), ~ replace_na(., 0)))
  
  return(df)
}

 normalized_data <- normalize_by_vehicle(cleaned_data)

fi_columns <- grep("_fi$", names(normalized_data), value = TRUE)
for (col in fi_columns) {
  new_col_name <- paste0(col, "_reciprocal")
  normalized_data[[new_col_name]] <- 1 / normalized_data[[col]]
}

pha_data <- normalized_data %>% filter(str_detect(Treatment, "PHA"))
lps_data <- normalized_data %>% filter(str_detect(Treatment, "LPS"))

columns <- c("live", "CD3", "CD4", "CD8", "CD3_fi", "CD4_fi", "CD8_fi","CD3_divided", "CD4_divided", "CD8_divided", "CD4_fi_reciprocal", "CD3_fi_reciprocal", "CD8_fi_reciprocal", "Ms", "Ms_fi_reciprocal", "Ms_divided")

create_datasets <- function(data, prefix) {
  map(columns, ~ data %>%
        select(Group, Treatment, Sex, Smokers, Chemical, all_of(.x)) %>%
        rename(Statistic = all_of(.x))) %>%
    set_names(paste0(prefix, "_", columns))
}

pha_datasets <- create_datasets(pha_data, "PHA")
lps_datasets <- create_datasets(lps_data, "LPS")
datasets <- c(pha_datasets, lps_datasets)
```

#PHA
##Heatmap PHA
```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})

selected_objects <- c("PHA_CD3_fi_reciprocal", "PHA_CD4_fi_reciprocal", "PHA_CD8_fi_reciprocal")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]

combined_data <- data.frame()
significance_results <- list()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  unique_chemicals <- unique(dataset$Chemical)

  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary)
    treatment_p <- tryCatch({
      treatment_effect <- anova_summary[[2]][[1]]  
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1     })
    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "PHA + Vehicle" | group2 %in% "PHA + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}

significance_df <- data.frame()


for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    significance_df <- rbind(significance_df, significance_labels)
}
}

significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
       significance_labels <- significance_results[[dataset_name]][[chem]]

    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    
    significance_df <- rbind(significance_df, significance_labels)
}
}
significance_df <- significance_df %>%
  arrange(chemical, dataset_name)

head(significance_df)

combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = sd(Statistic, na.rm = TRUE) / sqrt(n()),
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("CD3", dataset_name) ~ "CD3",
    grepl("CD4", dataset_name) ~ "CD4",
    grepl("CD8", dataset_name) ~ "CD8"
  )
  
  combined_data <- rbind(combined_data, mean_data)
}

filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )
for (i in 1:nrow(filtered_data)) {
  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%  
    select(significance) %>%
    pull()  
  

  if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {
      filtered_data$significance[i] <- NA  # Or any default value if no match
  }
}

filtered_data <- filtered_data %>%
  mutate(significance = ifelse(is.na(significance), "", significance))

treatment_levels <- c("Vehicle", "0.5", "12.5", "25", "50", "100")

filtered_data <- filtered_data %>%
  mutate(Treatment = factor(Treatment, levels = treatment_levels))

plot_file <- paste0(output_dir, "PHA_heat_nosig.png")
png(plot_file, width = 3000, height = 2000, res = 300)

heatmap_plot <- ggplot(filtered_data, aes(x = Marker, y = Treatment, fill = mean_stat)) +
  geom_tile(color = "white") + 
  geom_text(aes(label = significance), color = "black", size = 0) +  
  scale_fill_viridis_c(option = "plasma", name = "Relative % Divided", 
  limits =c(0.9, 1.8)) +
  labs(x = "T-cell Marker", y = "Treatment", title = "Heatmap of T-cell Proliferation") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  ) +
  facet_grid(~Chemical, space = "free", scales = "free", switch = "x")  


print(heatmap_plot)
dev.off()
plot_file <- paste0(output_dir, "PHA_heat_sig.png")
png(plot_file, width = 3000, height = 2000, res = 300)
heatmap_plot <- ggplot(filtered_data, aes(x = Marker, y = Treatment, fill = mean_stat)) +
  geom_tile(color = "white") +  
  geom_text(aes(label = significance), color = "black", size = 5) +  
  scale_fill_viridis_c(option = "plasma", name = "Relative % Divided", 
  limits =c(0.9, 1.8)) +  
  labs(x = "T-cell Marker", y = "Treatment", title = "Heatmap of T-cell Proliferation") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  ) +
  facet_grid(~Chemical, space = "free", scales = "free", switch = "x")  
print(heatmap_plot)
dev.off()
```



##Dose-response PHA

```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})


selected_objects <- c("PHA_CD3_divided", "PHA_CD4_divided", "PHA_CD8_divided")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]

combined_data <- data.frame()
significance_results <- list()


for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  unique_chemicals <- unique(dataset$Chemical)

  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary)
    treatment_p <- tryCatch({
      treatment_effect <- anova_summary[[2]][[1]]  
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1 
    })

    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "PHA + Vehicle" | group2 %in% "PHA + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}

significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    significance_df <- rbind(significance_df, significance_labels)
}
}
significance_df <- significance_df %>%
  arrange(chemical, dataset_name)

head(significance_df)

combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = std.error(Statistic) * 2.365,
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("CD3", dataset_name) ~ "CD3",
    grepl("CD4", dataset_name) ~ "CD4",
    grepl("CD8", dataset_name) ~ "CD8"
)
  
  combined_data <- rbind(combined_data, mean_data)
}


filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )

for (i in 1:nrow(filtered_data)) {
  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%
    select(significance) %>%
    pull() 
    if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {
    
    filtered_data$significance[i] <- NA  
  }
}


vehicle_data_ribbon <- filtered_data %>%
  filter(Treatment == "Vehicle") %>%
  group_by(Marker, Chemical) %>%
  summarise(
    ribbon_min = mean(mean_stat - se_stat, na.rm = TRUE),
    ribbon_max = mean(mean_stat + se_stat, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(
    filtered_data %>%
      group_by(Marker, Chemical) %>%
      summarise(
        x_min = min(log_Treatment, na.rm = TRUE),
        x_max = max(log_Treatment, na.rm = TRUE),
        .groups = "drop"
      ),
    by = c("Marker", "Chemical")
  ) %>%

  left_join(
    filtered_data %>%
      select(Marker, Chemical, log_Treatment, mean_stat) %>%
      distinct(),
    by = c("Marker", "Chemical")
  ) %>%
  mutate(log_Treatment = purrr::map2(x_min, x_max, ~seq(.x, .y, length.out = 100))) %>%
  unnest(cols = c(log_Treatment)) 

filtered_data$y_position_label <- filtered_data$mean_stat + filtered_data$se_stat + 5
filtered_data <- filtered_data %>%
  group_by(Chemical, Marker) %>%
  arrange(log_Treatment) %>%
  mutate(
    y_position_label = mean_stat + se_stat + 2 + (row_number() * 3)  
  ) %>%
  ungroup()

replicate_data <- do.call(rbind, filtered_datasets) %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order),
    Dataset = rep(names(filtered_datasets), times = sapply(filtered_datasets, nrow)),
   Marker = case_when(
      grepl("CD3", Dataset) ~ "CD3",
      grepl("CD4", Dataset) ~ "CD4",
      grepl("CD8", Dataset) ~ "CD8"
    ),
    Sex = ifelse(str_starts(Group, "M"), "Male", "Female")  
  )

plot_file <- paste0(output_dir, "PHA_nosig.png")
png(plot_file, width = 3750, height = 2100, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) +  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 125)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 0,
            check_overlap = FALSE)

print(plot)
dev.off()

plot_file <- paste0(output_dir, "PHA_sig.png")
png(plot_file, width = 3750, height = 2100, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) +  
  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 125)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 8,
            check_overlap = FALSE)

print(plot)
dev.off()
```

##Supplemental PHA
```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})

selected_objects <- c("PHA_CD3","PHA_CD4", "PHA_CD8", "PHA_live")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]

combined_data <- data.frame()
significance_results <- list()


for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  unique_chemicals <- unique(dataset$Chemical)
  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary)
    treatment_p <- tryCatch({
      treatment_effect <- anova_summary[[2]][[1]]  
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1  
    })
    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "PHA + Vehicle" | group2 %in% "PHA + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}
significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
        significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    
    significance_df <- rbind(significance_df, significance_labels)
}
}

significance_df <- significance_df %>%
  arrange(chemical, dataset_name)


head(significance_df)


combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = std.error(Statistic) * 2.365,
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("CD3", dataset_name) ~ "CD3",
    grepl("CD4", dataset_name) ~ "CD4",
    grepl("CD8", dataset_name) ~ "CD8",
    grepl("live", dataset_name) ~ "live"
)
  
  combined_data <- rbind(combined_data, mean_data)
}

filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )
for (i in 1:nrow(filtered_data)) {
  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%   
    select(significance) %>%
    pull()  
  
  if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {
  
    filtered_data$significance[i] <- NA  
  }
}

vehicle_data_ribbon <- filtered_data %>%
  filter(Treatment == "Vehicle") %>%
  group_by(Marker, Chemical) %>%
  summarise(
    ribbon_min = mean(mean_stat - se_stat, na.rm = TRUE),
    ribbon_max = mean(mean_stat + se_stat, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(
    filtered_data %>%
      group_by(Marker, Chemical) %>%
      summarise(
        x_min = min(log_Treatment, na.rm = TRUE),
        x_max = max(log_Treatment, na.rm = TRUE),
        .groups = "drop"
      ),
    by = c("Marker", "Chemical")
  ) %>%
  left_join(
    filtered_data %>%
      select(Marker, Chemical, log_Treatment, mean_stat) %>%
      distinct(),
    by = c("Marker", "Chemical")
  ) %>%
  mutate(log_Treatment = purrr::map2(x_min, x_max, ~seq(.x, .y, length.out = 100))) %>%
  unnest(cols = c(log_Treatment))  



filtered_data$y_position_label <- filtered_data$mean_stat + filtered_data$se_stat + 5
filtered_data <- filtered_data %>%
  group_by(Chemical, Marker) %>%
  arrange(log_Treatment) %>%
  mutate(
    y_position_label = mean_stat + se_stat + 2 + (row_number() * 3)  
  ) %>%
  ungroup()
replicate_data <- do.call(rbind, filtered_datasets) %>%
  group_by(Group, Treatment) %>%
  mutate(Replicate = row_number()) %>%
  ungroup() %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order),
    Dataset = rep(names(filtered_datasets), times = sapply(filtered_datasets, nrow)),
    Marker = case_when(
      grepl("CD3", Dataset) ~ "CD3",
      grepl("CD4", Dataset) ~ "CD4",
      grepl("CD8", Dataset) ~ "CD8",
      grepl("live", Dataset) ~ "live",
    ),
    Sex = ifelse(str_starts(Group, "M"), "Male", "Female")
  )

plot_file <- paste0(output_dir, "PHA_sup_nosig.png")
png(plot_file, width = 3750, height = 2800, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) +  
  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 125)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 0,
            check_overlap = FALSE)

print(plot)
dev.off()
plot_file <- paste0(output_dir, "PHA_sup_sig.png")
png(plot_file, width = 3750, height = 1500, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) + 
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 125)) +
  
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 8,
            check_overlap = FALSE)

print(plot)
dev.off()
```
#LPS
##Heatmap LPS
```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})
selected_objects <- c("LPS_CD3_fi_reciprocal", "LPS_CD4_fi_reciprocal", "LPS_CD8_fi_reciprocal")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]
combined_data <- data.frame()
significance_results <- list()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  unique_chemicals <- unique(dataset$Chemical)
  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary) treatment_p <- tryCatch({

      treatment_effect <- anova_summary[[2]][[1]] 
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1 
    })

    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "LPS + Vehicle" | group2 %in% "LPS + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}

significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    significance_df <- rbind(significance_df, significance_labels)
}
}

significance_df <- significance_df %>%
  arrange(chemical, dataset_name)


head(significance_df)


combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = sd(Statistic, na.rm = TRUE) / sqrt(n()),
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("CD3", dataset_name) ~ "CD3",
    grepl("CD4", dataset_name) ~ "CD4",
    grepl("CD8", dataset_name) ~ "CD8"
  )
  
  combined_data <- rbind(combined_data, mean_data)
}

filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )
for (i in 1:nrow(filtered_data)) {
  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%   
    select(significance) %>%
    pull()
  if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {

    filtered_data$significance[i] <- NA  
  }
}


filtered_data <- filtered_data %>%
  mutate(significance = ifelse(is.na(significance), "", significance))

treatment_levels <- c("Vehicle", "0.5", "12.5", "25", "50", "100")

filtered_data <- filtered_data %>%
  mutate(Treatment = factor(Treatment, levels = treatment_levels))
plot_file <- paste0(output_dir, "LPS_heat_nosig.png")
png(plot_file, width = 3000, height = 2000, res = 300)


heatmap_plot <- ggplot(filtered_data, aes(x = Marker, y = Treatment, fill = mean_stat)) +
  geom_tile(color = "white") + 
  geom_text(aes(label = significance), color = "black", size = 0) +
  scale_fill_viridis_c(option = "plasma", name = "Relative % Divided", 
  limits =c(0.9, 1.8)) +  
  labs(x = "T-cell Marker", y = "Treatment", title = "Heatmap of T-cell Proliferation") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  ) +
  facet_grid(~Chemical, space = "free", scales = "free", switch = "x") 


print(heatmap_plot)
dev.off()
plot_file <- paste0(output_dir, "LPS_heat_sig.png")
png(plot_file, width = 3000, height = 2000, res = 300)


heatmap_plot <- ggplot(filtered_data, aes(x = Marker, y = Treatment, fill = mean_stat)) +
  geom_tile(color = "white") + 
  geom_text(aes(label = significance), color = "black", size = 5) + 
  scale_fill_viridis_c(option = "plasma", name = "Relative % Divided", 
  limits =c(0.9, 1.8)) +  
  labs(x = "T-cell Marker", y = "Treatment", title = "Heatmap of T-cell Proliferation") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  ) +
  facet_grid(~Chemical, space = "free", scales = "free", switch = "x")

print(heatmap_plot)
dev.off()
```

##Dose-response LPS
```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})
selected_objects <- c("LPS_Ms_divided")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]
combined_data <- data.frame()
significance_results <- list()


for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  unique_chemicals <- unique(dataset$Chemical)

  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary)
    treatment_p <- tryCatch({
      treatment_effect <- anova_summary[[2]][[1]]  
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1  
    })

    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "LPS + Vehicle" | group2 %in% "LPS + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}

significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    significance_df <- rbind(significance_df, significance_labels)
}
}
significance_df <- significance_df %>%
  arrange(chemical, dataset_name)


head(significance_df)


combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = std.error(Statistic) * 2.365,
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("Ms", dataset_name) ~ "Non t-cells"
)
  
  combined_data <- rbind(combined_data, mean_data)
}

filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )
for (i in 1:nrow(filtered_data)) {
  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%  
    select(significance) %>%
    pull() if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {
    filtered_data$significance[i] <- NA  
  }
}


vehicle_data_ribbon <- filtered_data %>%
  filter(Treatment == "Vehicle") %>%
  group_by(Marker, Chemical) %>%
  summarise(
    ribbon_min = mean(mean_stat - se_stat, na.rm = TRUE),
    ribbon_max = mean(mean_stat + se_stat, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(
    filtered_data %>%
      group_by(Marker, Chemical) %>%
      summarise(
        x_min = min(log_Treatment, na.rm = TRUE),
        x_max = max(log_Treatment, na.rm = TRUE),
        .groups = "drop"
      ),
    by = c("Marker", "Chemical")
  ) %>%
  left_join(
    filtered_data %>%
      select(Marker, Chemical, log_Treatment, mean_stat) %>%
      distinct(),
    by = c("Marker", "Chemical")
  ) %>%
  mutate(log_Treatment = purrr::map2(x_min, x_max, ~seq(.x, .y, length.out = 100))) %>%
  unnest(cols = c(log_Treatment))  
filtered_data$y_position_label <- filtered_data$mean_stat + filtered_data$se_stat + 5
filtered_data <- filtered_data %>%
  group_by(Chemical, Marker) %>%
  arrange(log_Treatment) %>%
  mutate(
    y_position_label = mean_stat + se_stat + 2 + (row_number() * 3)
  ) %>%
  ungroup()
replicate_data <- do.call(rbind, filtered_datasets) %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order),
    Dataset = rep(names(filtered_datasets), times = sapply(filtered_datasets, nrow)),
    Marker = case_when(
      grepl("Ms", Dataset) ~ "Non t-cells",
      grepl("live", Dataset) ~ "Live"
    ),
    Sex = ifelse(str_starts(Group, "M"), "Male", "Female") 
  )

plot_file <- paste0(output_dir, "LPS_nosig.png")
png(plot_file, width = 3750, height = 1000, res = 300)

plot <- ggplot() +

  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) +  
  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 0,
            check_overlap = FALSE)

print(plot)
dev.off()

plot_file <- paste0(output_dir, "LPS.png")
png(plot_file, width = 3750, height = 1000, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) + 
  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 8,
            check_overlap = FALSE)

print(plot)
dev.off()
```

##Supplemental LPS
```{r}
chemical_order <- c("PFOS", "PFOA", "PFNA", "PFDA", "PFHxS", "GenX")

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})

selected_objects <- c("LPS_Ms", "LPS_live")
filtered_datasets <- datasets[names(datasets) %in% selected_objects]

combined_data <- data.frame()
significance_results <- list()


for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]

  unique_chemicals <- unique(dataset$Chemical)

  for (chem in unique_chemicals) {
    chem_data <- dataset %>% filter(Chemical == chem)
    anova_model <- aov(Statistic ~ Treatment + Error(Group/Treatment), data = chem_data)
    anova_summary <- summary(anova_model)
cat("\n\n=== ANOVA results for dataset:", dataset_name, "chemical:", chem, "===\n")
    print(anova_summary)
    treatment_p <- tryCatch({

      treatment_effect <- anova_summary[[2]][[1]] 
      p_val <- treatment_effect["Treatment", "Pr(>F)"]
      if (is.na(p_val)) 1 else p_val
    }, error = function(e) {
      1  
    })

    if (treatment_p < 0.05) {
      tukey_results <- emmeans(anova_model, pairwise ~ Treatment)
      pairwise_results <- as.data.frame(tukey_results$contrasts)

      pairwise_results <- pairwise_results %>%
        mutate(
          significance = case_when(
            p.value < 0.001 ~ "***",
            p.value < 0.01 ~ "**",
            p.value < 0.05 ~ "*",
            p.value >= 0.05 & p.value < 0.099 ~ ".",
            TRUE ~ ""
          )
        ) %>%
        separate(contrast, into = c("group1", "group2"), sep = " - ") %>%
        mutate(
          group1 = str_replace_all(group1, "[()]", ""),
          group2 = str_replace_all(group2, "[()]", "")
        )

      max_y <- max(chem_data$Statistic, na.rm = TRUE)
      increment <- max_y * 0.05

      significance_labels <- pairwise_results %>%
        filter(group1 %in% "LPS + Vehicle" | group2 %in% "LPS + Vehicle") %>%
        mutate(
          y.position = max_y + (row_number() - 1) * increment
        )

      if (!is.list(significance_results[[dataset_name]])) {
        significance_results[[dataset_name]] <- list()
      }
      significance_results[[dataset_name]][[chem]] <- significance_labels
    }
  }
}

significance_df <- data.frame()

for (dataset_name in names(significance_results)) {
  for (chem in names(significance_results[[dataset_name]])) {
    significance_labels <- significance_results[[dataset_name]][[chem]]
    significance_labels$chemical <- chem
    significance_labels$dataset_name <- dataset_name
    significance_df <- rbind(significance_df, significance_labels)
}
}

significance_df <- significance_df %>%
  arrange(chemical, dataset_name)

head(significance_df)

combined_data <- data.frame()

for (dataset_name in names(filtered_datasets)) {
  dataset <- filtered_datasets[[dataset_name]]
  
  mean_data <- dataset %>%
    group_by(Chemical, Treatment) %>%
    summarise(
      mean_stat = mean(Statistic, na.rm = TRUE),
      se_stat = std.error(Statistic) * 2.365,
      .groups = "drop"
    )
  
  mean_data$Dataset <- dataset_name
  mean_data$Marker <- case_when(
    grepl("Ms", dataset_name) ~ "Non T cells",
    grepl("live", dataset_name) ~ "live"
)
  
  combined_data <- rbind(combined_data, mean_data)
}

filtered_data <- combined_data %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order)
  )
significance_df <- significance_df %>%
  mutate(
    group2 = str_replace(group2, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim()
  )
for (i in 1:nrow(filtered_data)) {

  match_significance <- significance_df %>%
    filter(chemical == filtered_data$Chemical[i], 
           dataset_name == filtered_data$Dataset[i],
           group2 == filtered_data$Treatment[i]) %>%
    slice_head(n = 1) %>%  
    select(significance) %>%
    pull() 

  if (length(match_significance) == 1) {
    filtered_data$significance[i] <- match_significance
  } else {
    filtered_data$significance[i] <- NA 
  }
}


vehicle_data_ribbon <- filtered_data %>%
  filter(Treatment == "Vehicle") %>%
  group_by(Marker, Chemical) %>%
  summarise(
    ribbon_min = mean(mean_stat - se_stat, na.rm = TRUE),
    ribbon_max = mean(mean_stat + se_stat, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(
    filtered_data %>%
      group_by(Marker, Chemical) %>%
      summarise(
        x_min = min(log_Treatment, na.rm = TRUE),
        x_max = max(log_Treatment, na.rm = TRUE),
        .groups = "drop"
      ),
    by = c("Marker", "Chemical")
  ) %>%

  left_join(
    filtered_data %>%
      select(Marker, Chemical, log_Treatment, mean_stat) %>%
      distinct(),
    by = c("Marker", "Chemical")
  ) %>%
  mutate(log_Treatment = purrr::map2(x_min, x_max, ~seq(.x, .y, length.out = 100))) %>%
  unnest(cols = c(log_Treatment)) 

filtered_data$y_position_label <- filtered_data$mean_stat + filtered_data$se_stat + 5
filtered_data <- filtered_data %>%
  group_by(Chemical, Marker) %>%
  arrange(log_Treatment) %>%
  mutate(
    y_position_label = mean_stat + se_stat + 2 + (row_number() * 3) 
  ) %>%
  ungroup()
replicate_data <- do.call(rbind, filtered_datasets) %>%
  group_by(Group, Treatment) %>%
  mutate(Replicate = row_number()) %>%
  ungroup() %>%
  mutate(
    Treatment = str_replace(Treatment, "^(LPS|PHA)[ ]?(\\+ )?", "") %>%
                str_remove("uM") %>%
                str_trim(),
    log_Treatment = log10(as.numeric(replace(Treatment, Treatment == "Vehicle", "0")) + 1),
    Chemical = factor(Chemical, levels = chemical_order),
    Dataset = rep(names(filtered_datasets), times = sapply(filtered_datasets, nrow)),
    Marker = case_when(
      grepl("live", Dataset) ~ "live",
      grepl("Ms", Dataset) ~ "Non T cells"
    ),
    Sex = ifelse(str_starts(Group, "M"), "Male", "Female")
  )

plot_file <- paste0(output_dir, "LPS_sup_nosig.png")
png(plot_file, width = 3750, height = 1400, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
  geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) +  
    labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 100)) +

  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 0,
            check_overlap = FALSE)

print(plot)
dev.off()
plot_file <- paste0(output_dir, "LPS_sup_sig.png")
png(plot_file, width = 3750, height = 1400, res = 300)

plot <- ggplot() +
  geom_jitter(data = replicate_data,
           aes(x = log_Treatment, y = Statistic, fill = Chemical, color = Chemical, shape = Sex),
           stroke = 0.8,
           alpha =0.3,
           size = 1.5) +
  geom_point(data = filtered_data,
             aes(x = log_Treatment, y = mean_stat, color = Chemical),
             size = 2) +
  geom_errorbar(data = filtered_data,
                aes(x = log_Treatment, ymin = mean_stat - se_stat, ymax = mean_stat + se_stat, color = Chemical),
                width = 0.1) +
    geom_ribbon(data = vehicle_data_ribbon,
              aes(x = log_Treatment, ymin = ribbon_min, ymax = ribbon_max, fill = Chemical),
              inherit.aes = FALSE,
              alpha = 0.1) +
  
  facet_grid(Marker ~ Chemical, scales = "fixed") +
  scale_color_manual(values = custom_colors) +  
  scale_fill_manual(values = custom_colors) +
  scale_shape_manual(values = c(Male = 21, Female = 24)) + 
  
  labs(x = "Log10 Concentration (µM)", y = "Percentage Divided (%)", color = "Chemical", shape = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Arial", size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    panel.grid.major = element_line(size = 0.5),
    panel.grid.minor = element_blank()
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  geom_text(data = filtered_data[!is.na(filtered_data$significance), ],
            aes(x = log_Treatment, y = y_position_label, label = significance, color = Chemical),
            size = 8,
            check_overlap = FALSE)

print(plot)
dev.off()
```
#Extra Statitics
##Two-way ANOVA (sex/smoking)
```{r}
datasets <- c(pha_datasets, lps_datasets)

datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})
datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})

for (dataset_name in names(datasets)) {
  dataset <- datasets[[dataset_name]]
  dataset$Group <- as.factor(dataset$Group)
  dataset$Sex <- as.factor(dataset$Sex)
  dataset$Smokers <- as.factor(dataset$Smokers)
  dataset$Treatment <- as.factor(dataset$Treatment)
  model <- aov(Statistic ~ Sex * Smokers + Error(Group/Treatment), data = dataset)
  print(paste("Repeated Measures ANOVA results for dataset:", dataset_name))
  print(summary(model))
}
```

##Normal and vairance testing
```{r}

datasets <- c(pha_datasets, lps_datasets)
datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "PFHxS" & Group == "M4"))
})
datasets <- lapply(datasets, function(df) {
  df %>%
    filter(!(Chemical == "GenX" & Group == "F4"))
})
levene_results <- lapply(datasets, function(dataset) {
  leveneTest(Statistic ~ Treatment, data = dataset)
})


print(levene_results)

shapiro_results <- lapply(datasets, function(dataset) {
  shapiro.test(dataset$Statistic)
})

print(shapiro_results)

lapply(datasets, function(dataset) {
  qqnorm(dataset$Statistic)
  qqline(dataset$Statistic)
})
```


